delete unneeded notice function

diff --git a/zsh/functions/ssh-copy-id b/zsh/functions/ssh-copy-id
--- a/zsh/functions/ssh-copy-id
+++ b/zsh/functions/ssh-copy-id
@@ -7,12 +7,12 @@
 	fi
 
 	if [ -z "`eval $GET_ID`" ]; then
-	  notice "$0: ERROR: No identities found" >&2
+	  echo "$0: ERROR: No identities found" >&2
 	  return 1
 	fi
 
 	if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-	  notice "Usage: $0 [-i [identity_file]] [user@]machine" >&2
+	  echo "Usage: $0 [-i [identity_file]] [user@]machine" >&2
 	  return 1
 	fi
 
